// Phase 1 smoke tool for the vendored AutoRemesher core: OBJ in, quad OBJ out.
//
// This deliberately talks to the vendored headers directly instead of going
// through a trellis2 API — the point is to prove the core builds, runs, and
// produces sane numbers *before* any library wiring exists (that is Phase 3's
// quad_remesh.{h,cpp}). See docs/plan/autoremesher-quad-remesh.md.
//
//   quad_remesh_cli in.obj out.obj [--target-quads N] [--edge-scaling f]
//                                  [--adaptivity f] [--anisotropy f]
//                                  [--sharp-edge deg] [--smooth-normal deg]
//                                  [--hard-surface]
//
// Reports the measurements Phase 1 asks for: wall time, peak RSS, quad ratio,
// boundary edges, and surface-area retention. The last one is the proxy for
// silently dropped islands — AutoRemesher skips islands whose parameterization
// throws, and the API does not report that, so a large area loss is the only
// signal the caller gets.

#include <AutoRemesher/AutoRemesher>
#include <AutoRemesher/Vector3>

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <string>
#include <utility>
#include <vector>

#if defined( _WIN32 )
	#include <windows.h>
	#include <psapi.h>
#endif

namespace
{

// Peak resident set size in MiB, or -1 where we cannot ask cheaply.
double peak_rss_mib()
{
#if defined( _WIN32 )
	PROCESS_MEMORY_COUNTERS counters;
	if( GetProcessMemoryInfo( GetCurrentProcess(), &counters, sizeof( counters ) ) )
		return ( double )counters.PeakWorkingSetSize / ( 1024.0 * 1024.0 );
	return -1.0;
#elif defined( __linux__ )
	std::FILE* status = std::fopen( "/proc/self/status", "r" );
	if( !status )
		return -1.0;
	char   line[256];
	double kib = -1.0;
	while( std::fgets( line, sizeof( line ), status ) ) {
		if( std::strncmp( line, "VmHWM:", 6 ) == 0 ) {
			kib = std::atof( line + 6 );
			break;
		}
	}
	std::fclose( status );
	return kib < 0.0 ? -1.0 : kib / 1024.0;
#else
	return -1.0;
#endif
}

bool read_obj( const char* path, std::vector<AutoRemesher::Vector3>& verts, std::vector<std::vector<size_t>>& tris, std::string& err )
{
	std::FILE* file = std::fopen( path, "rb" );
	if( !file ) {
		err = std::string( "cannot open " ) + path;
		return false;
	}

	char line[1024];
	while( std::fgets( line, sizeof( line ), file ) ) {
		if( line[0] == 'v' && ( line[1] == ' ' || line[1] == '\t' ) ) {
			double x = 0.0, y = 0.0, z = 0.0;
			if( std::sscanf( line + 1, "%lf %lf %lf", &x, &y, &z ) == 3 )
				verts.push_back( AutoRemesher::Vector3( x, y, z ) );
		} else if( line[0] == 'f' && ( line[1] == ' ' || line[1] == '\t' ) ) {
			// Collect the polygon's vertex indices, ignoring the /vt/vn parts.
			std::vector<size_t> face;
			const char*			cursor = line + 1;
			while( *cursor ) {
				while( *cursor == ' ' || *cursor == '\t' )
					++cursor;
				if( *cursor == '\0' || *cursor == '\r' || *cursor == '\n' )
					break;
				const long index = std::strtol( cursor, nullptr, 10 );
				if( index > 0 ) {
					face.push_back( ( size_t )( index - 1 ) );
				} else if( index < 0 ) {
					const long resolved = ( long )verts.size() + index;
					if( resolved < 0 ) {
						err = "negative OBJ index out of range";
						std::fclose( file );
						return false;
					}
					face.push_back( ( size_t )resolved );
				}
				while( *cursor && *cursor != ' ' && *cursor != '\t' )
					++cursor;
			}
			// Fan-triangulate; the remesher takes triangles only.
			for( size_t i = 2; i < face.size(); ++i )
				tris.push_back( { face[0], face[i - 1], face[i] } );
		}
	}
	std::fclose( file );

	for( const auto& tri : tris ) {
		for( const size_t index : tri ) {
			if( index >= verts.size() ) {
				err = "OBJ face index out of range";
				return false;
			}
		}
	}
	if( verts.empty() || tris.empty() ) {
		err = "OBJ has no triangles";
		return false;
	}
	return true;
}

bool write_obj( const char* path, const std::vector<AutoRemesher::Vector3>& verts, const std::vector<std::vector<size_t>>& faces, std::string& err )
{
	std::FILE* file = std::fopen( path, "wb" );
	if( !file ) {
		err = std::string( "cannot write " ) + path;
		return false;
	}
	std::fprintf( file, "# generated by trellis2.cpp quad_remesh_cli\n" );
	for( const auto& v : verts )
		std::fprintf( file, "v %.8f %.8f %.8f\n", v.x(), v.y(), v.z() );
	for( const auto& face : faces ) {
		std::fprintf( file, "f" );
		for( const size_t index : face )
			std::fprintf( file, " %zu", index + 1 );
		std::fprintf( file, "\n" );
	}
	std::fclose( file );
	return true;
}

double polygon_area( const std::vector<AutoRemesher::Vector3>& verts, const std::vector<size_t>& face )
{
	// Fan decomposition; adequate for the near-planar faces produced here.
	double area = 0.0;
	for( size_t i = 2; i < face.size(); ++i )
		area += AutoRemesher::Vector3::area( verts[face[0]], verts[face[i - 1]], verts[face[i]] );
	return area;
}

double total_area( const std::vector<AutoRemesher::Vector3>& verts, const std::vector<std::vector<size_t>>& faces )
{
	double area = 0.0;
	for( const auto& face : faces )
		area += polygon_area( verts, face );
	return area;
}

// Edges used by exactly one face. Zero means closed; anything else means the
// output has holes, which is expected and is precisely why this path does not
// replace CGAL Alpha Wrap for printing.
size_t boundary_edges( const std::vector<std::vector<size_t>>& faces )
{
	std::map<std::pair<size_t, size_t>, int> counts;
	for( const auto& face : faces ) {
		for( size_t i = 0; i < face.size(); ++i ) {
			const size_t a = face[i], b = face[( i + 1 ) % face.size()];
			counts[std::make_pair( a < b ? a : b, a < b ? b : a )] += 1;
		}
	}
	size_t open = 0;
	for( const auto& entry : counts ) {
		if( entry.second == 1 )
			++open;
	}
	return open;
}

void report_progress( void* tag, float progress, const char* status )
{
	( void )tag;
	std::fprintf( stderr, "\r  %3d%%  %-40s", ( int )( progress * 100.0f ), status ? status : "" );
	std::fflush( stderr );
}

} // namespace

int main( int argc, char** argv )
{
	if( argc < 3 ) {
		std::fprintf( stderr,
			"usage: %s in.obj out.obj [--target-quads N] [--edge-scaling f]\n"
			"          [--adaptivity f] [--anisotropy f] [--sharp-edge deg]\n"
			"          [--smooth-normal deg] [--hard-surface]\n",
			argv[0] );
		return 2;
	}

	// Defaults mirror the upstream CLI (src/main.cpp).
	int	   target_quads		 = 50000;
	double edge_scaling		 = 0.0; // 0 -> leave unset, as upstream does
	double adaptivity		 = 1.0;
	double anisotropy		 = 1.0;
	double sharp_edge_deg	 = 90.0;
	double smooth_normal_deg = 0.0;
	bool   hard_surface		 = false;

	for( int i = 3; i < argc; ++i ) {
		const bool has_value = i + 1 < argc;
		if( std::strcmp( argv[i], "--target-quads" ) == 0 && has_value )
			target_quads = std::atoi( argv[++i] );
		else if( std::strcmp( argv[i], "--edge-scaling" ) == 0 && has_value )
			edge_scaling = std::atof( argv[++i] );
		else if( std::strcmp( argv[i], "--adaptivity" ) == 0 && has_value )
			adaptivity = std::atof( argv[++i] );
		else if( std::strcmp( argv[i], "--anisotropy" ) == 0 && has_value )
			anisotropy = std::atof( argv[++i] );
		else if( std::strcmp( argv[i], "--sharp-edge" ) == 0 && has_value )
			sharp_edge_deg = std::atof( argv[++i] );
		else if( std::strcmp( argv[i], "--smooth-normal" ) == 0 && has_value )
			smooth_normal_deg = std::atof( argv[++i] );
		else if( std::strcmp( argv[i], "--hard-surface" ) == 0 )
			hard_surface = true;
		else {
			std::fprintf( stderr, "unknown or incomplete option: %s\n", argv[i] );
			return 2;
		}
	}
	if( target_quads <= 0 ) {
		std::fprintf( stderr, "--target-quads must be positive\n" );
		return 2;
	}

	std::vector<AutoRemesher::Vector3> in_verts;
	std::vector<std::vector<size_t>>   in_tris;
	std::string						   err;
	if( !read_obj( argv[1], in_verts, in_tris, err ) ) {
		std::fprintf( stderr, "%s\n", err.c_str() );
		return 1;
	}
	const double in_area = total_area( in_verts, in_tris );
	std::fprintf( stderr, "in : %zu verts  %zu tris  area %.6f\n", in_verts.size(), in_tris.size(), in_area );

	AutoRemesher::AutoRemesher remesher( in_verts, in_tris );
	// Upstream maps target quads onto twice as many triangles (mainwindow.cpp).
	remesher.setTargetTriangleCount( ( size_t )target_quads * 2 );
	if( edge_scaling > 0.0 )
		remesher.setScaling( edge_scaling );
	remesher.setModelType( hard_surface ? AutoRemesher::ModelType::HardSurface : AutoRemesher::ModelType::Organic );
	remesher.setGradientAdaptivity( adaptivity );
	remesher.setAnisotropy( anisotropy );
	remesher.setSharpEdgeDegrees( sharp_edge_deg );
	remesher.setSmoothNormalDegrees( smooth_normal_deg );
	remesher.setProgressHandler( report_progress );

	const auto started	= std::chrono::steady_clock::now();
	const bool ok		= remesher.remesh();
	const auto finished = std::chrono::steady_clock::now();
	std::fprintf( stderr, "\r%-52s\r", "" );

	if( !ok ) {
		std::fprintf( stderr, "remesh failed\n" );
		return 1;
	}

	const std::vector<AutoRemesher::Vector3>& out_verts = remesher.remeshedVertices();
	const std::vector<std::vector<size_t>>&	  out_faces = remesher.remeshedQuads();
	if( out_faces.empty() ) {
		std::fprintf( stderr, "remesh produced no faces\n" );
		return 1;
	}

	size_t quads = 0, tris_out = 0, ngons = 0;
	for( const auto& face : out_faces ) {
		if( face.size() == 4 )
			++quads;
		else if( face.size() == 3 )
			++tris_out;
		else
			++ngons;
	}
	const double out_area = total_area( out_verts, out_faces );
	const double seconds  = std::chrono::duration<double>( finished - started ).count();
	const double rss	  = peak_rss_mib();

	std::fprintf( stderr, "out: %zu verts  %zu faces  area %.6f\n", out_verts.size(), out_faces.size(), out_area );
	std::fprintf( stderr, "     quads %zu (%.1f%%)  tris %zu  ngons %zu\n", quads, 100.0 * ( double )quads / ( double )out_faces.size(), tris_out, ngons );
	std::fprintf( stderr, "     boundary edges %zu%s\n", boundary_edges( out_faces ), boundary_edges( out_faces ) ? "  (open surface — not printable as is)" : "  (closed)" );
	std::fprintf( stderr, "     area retained %.1f%%%s\n", in_area > 0.0 ? 100.0 * out_area / in_area : 0.0, ( in_area > 0.0 && out_area < 0.9 * in_area ) ? "  (islands likely dropped)" : "" );
	std::fprintf( stderr, "     wall %.2f s", seconds );
	if( rss >= 0.0 )
		std::fprintf( stderr, "   peak RSS %.1f MiB", rss );
	std::fprintf( stderr, "\n" );

	if( !write_obj( argv[2], out_verts, out_faces, err ) ) {
		std::fprintf( stderr, "%s\n", err.c_str() );
		return 1;
	}
	std::fprintf( stderr, "wrote %s\n", argv[2] );
	return 0;
}
